// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcglxiuygxzxmbmajyxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjZ2x4aXV5Z3h6eG1ibWFqeXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDg4NzgsImV4cCI6MjA3MDY4NDg3OH0.6a82Au0DT_mNUBm3frWxzSfuR9i-P1XrLRkCXuU327k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});